/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');
// import dependencies from package.json, which includes react and react-dom
const { dependencies } = require('../../package.json');
const port = require('../../server/port');

module.exports = require('./webpack.base.babel')({
  mode: 'development',

  // Add hot reloading in development
  entry: './app/entry.js', // Start with js/app.js

  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
    publicPath: `http://localhost:/${port}`,
  },

  optimization: {
    splitChunks: {
      chunks: 'async',
    },
  },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'app/index.html',
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
    // new BundleAnalyzerPlugin({
    //   analyzerPort: 8006,
    // }),
    new ModuleFederationPlugin({
      name: 'HeaderApp', // This application named 'HeaderApp'
      filename: 'remoteEntry.js', // output a js file
      exposes: {
        // which exposes
        './Label': './app/components/atoms/Label/index.js', // a module 'Header' from './src/App'
      },
      shared: {
        // and shared
        ...dependencies, // some other dependencies
        react: {
          // react
          singleton: true,
          requiredVersion: dependencies['react'],
        },
        'react-dom': {
          // react-dom
          singleton: true,
          requiredVersion: dependencies['react-dom'],
        },
        'prop-type': {
          singleton: true,
          requiredVersion: dependencies['prop-type'],
        },
      },
    }),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'cheap-module-source-map',

  performance: {
    hints: false,
  },
});
